Neo Geo Hack adjustments
finalburnneo/FBNeo pull request #519
Opened 2020-10-22 18:54 UTC by WandeingLagomorph793

Assorted hacks for the Neo Geo, primarily secret character hacks for Fatal Fury, Art of Fighting and King of Fighters. Still have a few more, primarily from World Heroes and Samurai Shodown, but for now this is a new batch.

I readjusted their position to line 18635 as per suggestion, as well as adjusting the newer hacks to the CLONE and HACK tags specifically, I also adjusted the parent files under suggestion, so for example

   { "092-p1.p1",    0x200000, 0x28ec9b77, 1 | BRF_ESS | BRF_PRG }, //  0 68K code 		/ mask rom TC5316200
    { "092-p1bh.p1",    0x200000, 0x9E814A43, 1 | BRF_ESS | BRF_PRG }, //  1 68K code 		/ mask rom TC5316200

Since I feel like part of what was causing problems before was only one of those being present, for those I readjusted the numbers to count down as they should instead of 0,0 1, 2 or however.

These hacks originate from this link here, I don't think I can link his MEGA link due to potential violations but his channel covers a lot of these. Some of them like KOF97ps1 came from elsewhere.
https://www.youtube.com/user/AdmiralMcFish
These come with an FB executable within, not modified but just older, so I tested these with that and can confirm they worked, though since it was mentioned that Samurai Shodown I gave problems in the last PR, I'm gonna remove that one until I can better confirm that and put it in with it's series. Could be a typo on my end as well but I'll look into it further.

dinkc64 mentioned the repo assuming that I authored the entire file, this was mentioned in one of the older PR's from last time as well and I'm uncertain as to what causes this one. If it's still happening now then I'm not really sure how to solve that one.

2020-10-22 20:09 UTC, dankcushions commented
white space issues again...

2020-10-22 20:18 UTC, barbudreadmon requested changes

2020-10-22 20:18 UTC, barbudreadmon commented on src/burn/drv/neogeo/d_neogeo.cpp
> +	"garoubh", NULL, "neogeo", NULL, "1999",
parents are still missing, here it should be : 
```
"garoubh", "garou", "neogeo", NULL, "1999",
```
Same for every romsets

2020-10-22 20:22 UTC, WandeingLagomorph793 commented
> white space issues again...

Anywhere in particular @dankcushions ?, I'm comparing to both the formatting of the normal file and the resolves from last time and I'm still not sure what's causing those.

@barbudreadmon Gotcha, so I know in advance, testing with garou now as above, I'm guessing it's this

struct BurnDriver BurnDrvGaroubh = {
	"garoubh", "garou" NULL, "neogeo", NULL, "1999",
	"Garou - Mark of the Wolves (Boss Hack)\0", NULL, "SNK", "Neo Geo MVS",
	L"Garou\0\u9913\u72FC - mark of the wolves (Boss Hack)\0", NULL, NULL, NULL,
	BDF_GAME_WORKING | BDF_CLONE |  BDF_HACK | BDF_HISCORE_SUPPORTED, 2, HARDWARE_PREFIX_CARTRIDGE | HARDWARE_SNK_NEOGEO | HARDWARE_SNK_CMC42 | HARDWARE_SNK_SMA_PROTECTION, GBF_VSFIGHT, 0,
	NULL, garoubhRomInfo, garoubhRomName, NULL, NULL, NULL, NULL, neogeoInputInfo, neogeoDIPInfo,
	garouInit, NeoSMAExit, NeoFrame, NeoRender, NeoScan, &NeoRecalcPalette,
	0x1000, 320, 224, 4, 3
};

Is that fine or would I need to adjust NULL too? I'm wanting to make sure before going in to adjust that.

2020-10-22 21:19 UTC, barbudreadmon commented
> "garoubh", "garou" NULL, "neogeo", NULL, "1999",

no NULL next to "garou", "garou" is the parent, NULL means there is no parent.

2020-10-22 21:31 UTC, WandeingLagomorph793 commented
> > "garoubh", "garou" NULL, "neogeo", NULL, "1999",
> 
> no NULL next to "garou", "garou" is the parent, NULL means there is no parent.

got it, I'll remove that and check through again for the others, I'm gonna guess that the format is "hack name" "parent name", not sure if I need to remove that second NULL or if that one's fine but I'm gonna start with this first. Hoping I can get those spacing problems sorted out, no idea whats causing those.

2020-10-23 00:11 UTC, dinkc64 commented
@WandeingLagomorph793 
Do you have a compiler set up to test your code?  If you need help setting one up, I have a self-contained portable fbneo-compiling compiler that is really simple to install.

2020-10-23 00:14 UTC, WandeingLagomorph793 commented
> @WandeingLagomorph793
> Do you have a compiler set up to test your code? If you need help setting one up, I have a self-contained portable fbneo-compiling compiler that is really simple to install.

Been compiling manually via git and it's not the fastest, not sure if the self contained one would work on my system due to OS differences but it's certainly worth a shot.

2020-10-23 02:44 UTC, dinkc64 commented
@WandeingLagomorph793 
This compiler will work with win2k,winxp,winvista,win7,8,10.
Just unzip to c:\
from a cmd prompt, run mingw\bin\mingw_start.bat
then - from the same cmd prompt - change to the fbneo source directory (usually fbneo-master\trunk) and run:
makefbn.bat
or makefbni7.bat if you have an i5/i7 processor with 4+ cores - it will compile a lot faster this way.

best regards,
- dink

2020-10-23 02:52 UTC, WandeingLagomorph793 commented
> @WandeingLagomorph793
> This compiler will work with win2k,winxp,winvista,win7,8,10.
> Just unzip to c:
> from a cmd prompt, run mingw\bin\mingw_start.bat
> then - from the same cmd prompt - change to the fbneo source directory (usually fbneo-master\trunk) and run:
> makefbn.bat
> or makefbni7.bat if you have an i5/i7 processor with 4+ cores - it will compile a lot faster this way.
> 
> best regards,
> 
>     * dink

Using Linux so sadly not sure if that would work :(. I could still give it a shot with WINE though not sure how well command line tools work with it, still doesn't hurt to try it.

2020-10-23 03:14 UTC, closed without merging

2020-10-23 08:48 UTC, dankcushions commented
> > white space issues again...
> 
> Anywhere in particular @dankcushions ?, I'm comparing to both the formatting of the normal file and the resolves from last time and I'm still not sure what's causing those.

isn't it obvious? have a look in the 'files changed' tab in this PR and the [6th item in the struct](https://github.com/finalburnneo/FBNeo/pull/519/files#diff-88b13e530abcab9b5f53758e56a470b1faa68ac14c533f629fa959449c44cbc8R18645) is out of horizontal alignment with the surrounding items. you can scroll through quickly and these types of issues jump out. there are many like this - this is exactly the same as the ones i pointed out in the previous PR.

what text editor are you using? [sublime text](https://www.sublimetext.com/) shows tabs as a strikethrough, and spaces as dots, so it's very obvious when scanning through code where you've used spaces rather than tabs, or vice versa, even if they visually appear correctly aligned.

note that if you're copying and pasting chunks of code to modify, you may be inheriting other people's white space issues, but still, we should always fix up our own code...

2020-10-23 09:26 UTC, WandeingLagomorph793 commented
> > > white space issues again...
> > 
> > 
> > Anywhere in particular @dankcushions ?, I'm comparing to both the formatting of the normal file and the resolves from last time and I'm still not sure what's causing those.
> 
> isn't it obvious? have a look in the 'files changed' tab in this PR and the [6th item in the struct](https://github.com/finalburnneo/FBNeo/pull/519/files#diff-88b13e530abcab9b5f53758e56a470b1faa68ac14c533f629fa959449c44cbc8R18645) is out of horizontal alignment with the surrounding items. you can scroll through quickly and these types of issues jump out. there are many like this - this is exactly the same as the ones i pointed out in the previous PR.
> 
> what text editor are you using? [sublime text](https://www.sublimetext.com/) shows tabs as a strikethrough, and spaces as dots, so it's very obvious when scanning through code where you've used spaces rather than tabs, or vice versa, even if they visually appear correctly aligned.
> 
> note that if you're copying and pasting chunks of code to modify, you may be inheriting other people's white space issues, but still, we should always fix up our own code...

Using Linux so I'm using Kwrite and Kate primarily, Kwrite not showing any different at all and Kate showing when it's tabbed but not saving it regardless.

I still got a few more for Neo Geo but I think it's probably best I don't send another PR given how that's gone, I sincerely apologize on that one.

2020-10-23 09:56 UTC, barbudreadmon commented
> Using Linux

On linux, i use "geany", you can set it to show indentation guides (Preference > Editor > Display), which helps a lot with this.

2020-10-23 10:07 UTC, WandeingLagomorph793 commented
> > Using Linux
> 
> On linux, i use "geany", you can set it to show indentation guides (Preference > Editor > Display), which helps a lot with this.

Not sure if Kate or KWrite have an equivalent, I'll check that but thanks for the tip with geany, never heard of that one so I'll give that a shot.

I got some more hacks for Neo Geo and a few other systems, I had one for PGM but that seems to be taken care of when I checked the PGM file, would it be an issue if I just sent in the CRC checksums and went from there if needed? I apologize for how the PR mess went on my end and I'd rather not waste peoples time by repeating that.

2020-10-23 13:38 UTC, dinkc64 commented
@WandeingLagomorph793 
You didn't waste anyone's time, at best, you probably learned a few things.
On Linux you can build the SDL2 version and test on that before submitting a pr, this way you can get it perfect beforehand and everything will look good.  

best regards,
- dink

2020-10-23 18:41 UTC, WandeingLagomorph793 commented
> @WandeingLagomorph793
> You didn't waste anyone's time, at best, you probably learned a few things.
> On Linux you can build the SDL2 version and test on that before submitting a pr, this way you can get it perfect beforehand and everything will look good.
> 
> best regards,
> 
>     * dink

i'll try giving that one a shot, i still got some more hacks to submit later to round off the Neo Geo, alongside Capcom and Asura Buster though I hadn't found where Asura would be, not sure the best way to build the SDL2 but I'll give that a shot, if that goes poorly then I'm probably just going to send the appropriate checksums and leave it at that until further material is required.